import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { DarkProvider } from '@/modules/context/themeProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cnippet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkProvider>
          {children}
        </DarkProvider>
      </body>
    </html>
  );
}
